-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "password" TEXT,
    "cloudflareId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "Application" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "logoUrl" TEXT,
    "publicUrl" TEXT,
    "destinationType" TEXT NOT NULL,
    "destinationUrl" TEXT NOT NULL,
    "exposureType" TEXT NOT NULL,
    "tunnelId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "dnsRecordId" TEXT
);

-- CreateTable
CREATE TABLE "Configuration" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "value" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "CloudflareDNSLog" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "query" TEXT NOT NULL,
    "query_type" TEXT NOT NULL,
    "policy_uuid" TEXT NOT NULL,
    "location_uuid" TEXT NOT NULL,
    "source_ip" TEXT NOT NULL,
    "destination_ip" TEXT NOT NULL,
    "destination_port" INTEGER NOT NULL,
    "protocol" TEXT NOT NULL,
    "datetime" DATETIME NOT NULL,
    "decision" TEXT NOT NULL,
    "blocked" BOOLEAN NOT NULL,
    "overridden" BOOLEAN NOT NULL,
    "query_category_ids" JSONB NOT NULL,
    "initial_category_ids" JSONB NOT NULL,
    "cname_category_ids" JSONB,
    "rdata" JSONB NOT NULL,
    "email" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "device_id" TEXT NOT NULL,
    "dnssec_validation_disabled" BOOLEAN NOT NULL,
    "ede_errors" JSONB NOT NULL,
    "src_country" TEXT NOT NULL,
    "tenant_configuration_account_id" TEXT NOT NULL,
    "host_application_id" INTEGER,
    "rcode" INTEGER NOT NULL,
    "time_zone_inferred_method" TEXT NOT NULL,
    "custom_resolver_address" TEXT NOT NULL,
    "custom_resolver_response" TEXT NOT NULL,
    "custom_resolver_time_in_ms" INTEGER NOT NULL,
    "custom_resolver_rule_uuid" TEXT NOT NULL,
    "is_response_cached" BOOLEAN NOT NULL,
    "colo_id" INTEGER NOT NULL,
    "metal_id" INTEGER NOT NULL,
    "resolved_ips" JSONB NOT NULL,
    "authoritative_nameserver_ips" JSONB NOT NULL,
    "doh_subdomain" TEXT NOT NULL,
    "dot_subdomain" TEXT,
    "resolved_country_codes" JSONB NOT NULL,
    "resolved_continent_codes" JSONB NOT NULL,
    "src_country_code" TEXT NOT NULL,
    "src_continent_code" TEXT NOT NULL,
    "cnames" JSONB NOT NULL,
    "query_id" TEXT NOT NULL,
    "resolver_rule_id" TEXT,
    "internal_dns_rcode" INTEGER NOT NULL,
    "internal_dns_time_in_ms" INTEGER NOT NULL,
    "redirect_target_uri" TEXT NOT NULL,
    "registration_id" TEXT NOT NULL,
    "query_application_ids" JSONB,
    "matched_tunnel_type" INTEGER NOT NULL,
    "response_time_ms" INTEGER NOT NULL
);

-- CreateTable
CREATE TABLE "CloudflareNetworkLog" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "session_id" TEXT NOT NULL,
    "datetime" DATETIME NOT NULL,
    "account_id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "device_id" TEXT NOT NULL,
    "virtual_network_id" TEXT NOT NULL,
    "rule_id" TEXT NOT NULL,
    "action" INTEGER NOT NULL,
    "action_name" TEXT NOT NULL,
    "source_ip" TEXT NOT NULL,
    "source_internal_ip" TEXT NOT NULL,
    "source_port" INTEGER NOT NULL,
    "destination_ip" TEXT NOT NULL,
    "destination_port" INTEGER NOT NULL,
    "override_ip" TEXT NOT NULL,
    "override_port" INTEGER NOT NULL,
    "transport" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "sni" TEXT NOT NULL,
    "last_authenticated_at" DATETIME NOT NULL,
    "src_country" TEXT NOT NULL,
    "dst_country" TEXT NOT NULL,
    "src_continent" TEXT NOT NULL,
    "dst_continent" TEXT NOT NULL,
    "proxy_endpoint" TEXT NOT NULL,
    "detected_protocol" TEXT NOT NULL,
    "access_app_auds" JSONB NOT NULL,
    "colo_id" INTEGER NOT NULL,
    "metal_id" INTEGER NOT NULL,
    "application_ids" JSONB NOT NULL,
    "category_ids" JSONB NOT NULL,
    "redirect_target_uri" TEXT NOT NULL,
    "registration_id" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "CloudflareHTTPLog" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "session_id" TEXT NOT NULL,
    "datetime" DATETIME NOT NULL,
    "request_id" TEXT NOT NULL,
    "account_id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "device_id" TEXT NOT NULL,
    "rule_id" TEXT NOT NULL,
    "action" INTEGER NOT NULL,
    "action_name" TEXT NOT NULL,
    "is_isolated" BOOLEAN NOT NULL,
    "http_host" TEXT NOT NULL,
    "http_method" INTEGER NOT NULL,
    "http_method_name" TEXT NOT NULL,
    "http_version" INTEGER NOT NULL,
    "http_version_name" TEXT NOT NULL,
    "http_status_code" INTEGER NOT NULL,
    "url" TEXT NOT NULL,
    "referer" TEXT NOT NULL,
    "user_agent" TEXT NOT NULL,
    "source_ip" TEXT NOT NULL,
    "source_internal_ip" TEXT NOT NULL,
    "source_port" INTEGER NOT NULL,
    "destination_ip" TEXT NOT NULL,
    "destination_port" INTEGER NOT NULL,
    "uploaded_file_names" JSONB NOT NULL,
    "downloaded_file_names" JSONB NOT NULL,
    "upload_matched_dlp_profiles" JSONB NOT NULL,
    "download_matched_dlp_profiles" JSONB NOT NULL,
    "upload_matched_dlp_profileEntries" JSONB NOT NULL,
    "download_matched_dlp_profileEntries" JSONB NOT NULL,
    "dlp_match_context" TEXT NOT NULL,
    "dlp_match_context_parsed" TEXT,
    "file_info" JSONB NOT NULL,
    "blocked_file_name" TEXT NOT NULL,
    "blocked_file_type" TEXT NOT NULL,
    "blocked_file_hash" TEXT NOT NULL,
    "blocked_file_size" INTEGER NOT NULL,
    "blocked_file_reason" INTEGER NOT NULL,
    "added_headers" JSONB NOT NULL,
    "last_authenticated_at" DATETIME NOT NULL,
    "request_antivirus_scanned" BOOLEAN NOT NULL,
    "response_antivirus_scanned" BOOLEAN NOT NULL,
    "quarantined" BOOLEAN NOT NULL,
    "src_country" TEXT NOT NULL,
    "dst_country" TEXT NOT NULL,
    "src_continent" TEXT NOT NULL,
    "dst_continent" TEXT NOT NULL,
    "proxy_endpoint" TEXT NOT NULL,
    "untrusted_cert_action" TEXT NOT NULL,
    "access_app_aud" TEXT NOT NULL,
    "colo_id" INTEGER NOT NULL,
    "metal_id" INTEGER NOT NULL,
    "application_ids" JSONB NOT NULL,
    "application_type_ids" JSONB NOT NULL,
    "category_ids" JSONB NOT NULL,
    "virtual_network_id" TEXT NOT NULL,
    "forensic_copy_status" TEXT NOT NULL,
    "redirect_target_uri" TEXT NOT NULL,
    "registration_id" TEXT NOT NULL,
    "gen_ai_prompt_request" TEXT NOT NULL,
    "gen_ai_prompt_response" TEXT NOT NULL,
    "gen_ai_conversation" TEXT NOT NULL,
    "application_statuses" JSONB NOT NULL,
    "app_control_info" JSONB NOT NULL,
    "upload_matched_dlp_data_classes" JSONB NOT NULL,
    "download_matched_dlp_data_classes" JSONB NOT NULL,
    "upload_matched_dlp_data_tags" JSONB NOT NULL,
    "download_matched_dlp_data_tags" JSONB NOT NULL,
    "upload_matched_dlp_sensitivity_levels" JSONB NOT NULL,
    "download_matched_dlp_sensitivity_levels" JSONB NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE UNIQUE INDEX "CloudflareDNSLog_query_id_key" ON "CloudflareDNSLog"("query_id");

-- CreateIndex
CREATE UNIQUE INDEX "CloudflareNetworkLog_session_id_key" ON "CloudflareNetworkLog"("session_id");

-- CreateIndex
CREATE UNIQUE INDEX "CloudflareHTTPLog_request_id_key" ON "CloudflareHTTPLog"("request_id");
